# --------------------- #
#    Generation File    #
# --------------------- #

# Other generation files to import. (Example: intensive_apps -> ~/.config/rebos/imports/intensive_apps.toml)
imports = [
    # "intensive_apps",
]

# Packages to be installed via the native package manager.
[managers.system]
items = [
	# apps
	"ungoogled-chromium-bin",
	"zen-browser",

	# cli
	"gvfs-onedrive",
	
	# dev
	"openjdk21-src",
	"openjdk21-doc",
	"python-pip",

	# docker
	"docker",
	"docker-buildx",
	"docker-compose",

	# fonts
	"ttf-jetbrains-mono",
	"ttf-jetbrains-mono-nerd",
]

# Packages to be installed via Flatpak.
[managers.flatpak]
items = [
	# essentials
	"bottles",
]
