[window]
title = "Terminal"
dynamic_title = true
dynamic_padding = true
startup_mode = "Maximized"

[window.padding]
x = 0
y = 0

[shell]
program = "/usr/bin/zsh"

[env]
LANG = "en_US.UTF-8"
LC_CTYPE = "en_US.UTF-8"
TERM = "alacritty"

[mouse]
hide_when_typing = true

[font]
size = 9.5

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"
