[managers.system]
items = [
	"kde-connect",			# mobile connection
	"nextcloud-client",		# cloud client
	"obs-studio",			# screen recording tool
	"flameshot",			# screenshot tool
	"vlc",					# media player
	"chromium",				# chromium browser for usage with VIA
	"virt-manager",			# virtual machine manager
]

[managers.flatpak]
items = [
	"org.signal.Signal",
	"com.spotify.Client",					# music B)
	"dev.vencord.Vesktop",					# 3rd party discord client for wayland streaming
]
