[managers.system]
items = [
	"discord",                   # discord communication app
	"kde-connect",               # mobile connection
	"nextcloud-client",          # cloud client
	"obs-studio",                # screen recording tool
	"flameshot",                 # screenshot tool
	"vlc",                       # media player
	"heroic-games-launcher-bin", # heroic games launcher (depending on COPR repo)
	"chromium",                  # chromium browser for usage with VIA
]

[managers.flatpak]
items = ["com.spotify.Client"] # music B)
