[managers.system]
items = [
	"kde-connect",			# mobile connection
	#"nextcloud-client",		# cloud client
	"obs-studio",			# screen recording tool
	"flameshot",			# screenshot tool
	"vlc",					# media player
	"chromium",				# chromium browser for usage with VIA
	"virt-manager",			# virtual machine manager
	"zen-browser-avx2",		# best browser in existence
]

[managers.flatpak]
items = [
	"com.spotify.Client",					# music B)
	"dev.vencord.Vesktop",					# 3rd party discord client for wayland streaming
	"page.kramo.Cartridges",				# uniform game launcher
	"com.jeffser.Alpaca",					# Ollama client
	"dev.bragefuglseth.Keypunch",			# typing speed practice
	"com.dec05eba.gpu_screen_recorder",		# guess what: gpu screen recorder :)
	"io.missioncenter.MissionCenter",		# better system monitor
	"com.notesnook.Notesnook",				# note taking
	"io.gitlab.theevilskeleton.Upscaler",	# image upscaling
	"com.hunterwittenborn.Celeste",			# cloud sync gui (rclone)
]
