[managers.system]
items = [
	"snapper",                # btrfs snapshot tool
	"plymouth-plugin-script", # plymouth boot screen theme loader script
	# LogiOps G502 support dependencies
	"cmake",
	"libevdev-devel",
	"libudev-devel",
]
