[managers.system]
items = [
	"snapper",                # btrfs snapshot tool
	"plymouth-plugin-script", # plymouth boot screen theme loader script
	"piper",                  # GUI for mouse configuration
]
