[managers.system]
items = [
	"snapper",                # btrfs snapshot tool
	"plymouth-plugin-script", # plymouth boot screen theme loader script
	# LogiOps G502 support dependencies
	"cmake",
	"libevdev-devel",
	"libudev-devel",
	"glib2-devel",
	"libconfig-devel",
	"gtk3",
	"webkit2gtk4.1",
	"libusb",
]
