# --------------------- #
#    Generation File    #
# --------------------- #

# Other generation files to import. (Example: intensive_apps -> ~/.config/rebos/imports/intensive_apps.toml)
imports = [
	# "intensive_apps",
	"docker", # containers :D
]

# Packages to be installed via the native package manager.
[managers.system]
items = [
	"git",                      # version control
	"alacritty",                # best terminal emulator
	"zsh",                      # z shell
	"discord",                  # discord communication app
	"flatpak",                  # flatpak package manager
	"fzf",                      # fuzzy finder
	"jetbrains-mono-fonts",     # main mono font
	"jetbrainsmono-nerd-fonts", # nerd font ;)
	"kde-connect",              # mobile connection
	"ncdu",                     # file size inspector (like TreeSize)
	"neovim",                   # editor
	"nextcloud-client",         # cloud client
	"nodejs",                   # js runtime
	"obs-studio",               # screen recording tool
	"snapper",                  # btrfs snapshot tool
	"stow",                     # parent directory linker (for dotfiles)
	"texlive-scheme-full",      # latex packages
	"code",                     # vs code
	"cargo",                    # rust cargo package manager
	"plymouth-plugin-script",   # plymouth boot screen theme loader script
	"exa",                      # better ls
	"bat",                      # better cat
	"ripgrep",                  # cli file content seaercher
	"zoxide",                   # better cd
	"mc",                       # cli file manager
	"flameshot",                # screenshot tool
	"htop",                     # cli system process monitor
	"vlc",                      # media player
	"zed",                      # better vs code (probably), built on rust, less extensions (obviously)
]

# Packages to be installed via Flatpak.
[managers.flatpak]
items = ["com.spotify.Client"] # music B)

# Packages to be installed via Cargo.
[managers.cargo]
items = [
	# "bacon",
]
