# --------------------- #
#    Generation File    #
# --------------------- #

# Other generation files to import. (Example: intensive_apps -> ~/.config/rebos/imports/intensive_apps.toml)
imports = [
	# "intensive_apps",
	"docker",
	"vscode",
]

[managers.system-repos]
items = ["https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo"]

# Packages to be installed via the native package manager.
[managers.system]
items = [
	"git",
	"alacritty",
	"zsh",
	#	"code",
	"discord",
	"flatpak",
	"fzf",
	"jetbrains-mono-fonts",
	"jetbrainsmono-nerd-fonts",
	"kde-connect",
	"ncdu",
	"neovim",
	"nextcloud-client",
	"nodejs",
	"obs-studio",
	"snapper",
	"stow",
	"texlive-scheme-full",
]

# Packages to be installed via Flatpak.
[managers.flatpak]
items = ["com.spotify.Client"]

# Packages to be installed via Cargo.
[managers.cargo]
items = [
	# "bacon",
]
